### PR TITLE
Create espenhermansen-ubernetes-challenge.md

### PR DESCRIPTION
**Pull request by espenhermansen**

### CODE REVIEW

**Review by OliverMensahDev — CHANGES_REQUESTED** [review]
Awesome work @espenhermansen .

Kindly include in your write-up some screenshots of the DO dashboard or screenshots of a few commands that you used in creating the DOKS.

**Comment by espenhermansen** [comment]
I have added some printscreen of the Kubernetes cluster in DigitalOcean.
I used Terraform to create the cluster, the code is in the same repo
https://github.com/espenhermansen/kube_challenge_log_mon/tree/main/terraform

Thanks :)

**Review by OliverMensahDev — COMMENTED** [review]
@espenhermansen  the PR is closed now, any reason why you did that?

**Comment by espenhermansen** [comment]
Hi, i did by mistake. Sorry :)

**Pull request merged**
