### PR TITLE
Added 2801nayan kubernetes-challenge file

### PR DESCRIPTION
**Pull request by 2801nayan**

### CODE REVIEW

**Review by OliverMensahDev — CHANGES_REQUESTED** [review]
Awesome work @2801nayan,

With the steps, can you include some screenshots that show that you actually created the DOKS or screenshots of a few commands that you used?

**Comment by 2801nayan** [comment]
Hello @OliverMensahDev Thanks for reviewing the PR 
I am adding the Stepwise Snapshots in this comment, please have a look 
d1

d2

d3

d4

d5

d6

d7

**Comment by 2801nayan** [comment]
Hello @OliverMensahDev @kimschles  I have  uploaded the snapshots as per the request could you please review it as i need to destroy the cluster as my credits have came to an end

**Comment by OliverMensahDev** [comment]
That's awesome, @2801nayan,

My bad, I should have been specific. 
They should be included in your write-up where you mentioned creating the cluster.

**Comment by 2801nayan** [comment]
Hello @OliverMensahDev @kimschles I have Added the Readme with the snapshots and also link to my blog . please have a look and review it

**Comment by kimschles** [comment]
You're all set. Thank you for updating your readme!

**Pull request merged**
