### PR TITLE
Create victorakaps-DO-k8s-NoSQL

### PR DESCRIPTION
**Pull request by victorakaps**

### CODE REVIEW

**Review by OliverMensahDev — CHANGES_REQUESTED** [review]
The file you submitted must be a markdown file instead.

**Comment by victorakaps** [comment]
> The file you submitted must be a markdown file instead.

made required changes

**Review by OliverMensahDev — CHANGES_REQUESTED** [review]
Awesome writeup, @victorakaps 

With the steps, can you include some screenshots that show that you actually created the DOKS or screenshots of a few commands that you used?

**Comment by victorakaps** [comment]
> Awesome writeup, @victorakaps
> 
> With the steps, can you include some screenshots that show that you actually created the DOKS or screenshots of a few commands that you used?

added screenshot of DO Dashboard featuring the k8 cluster that i created under Step 1 in my writeup.

**Review by OliverMensahDev — APPROVED** [review]

**Pull request merged**
