### PR TITLE
Kubernetes challenge entry

### PR DESCRIPTION
**Pull request by Sossenbinder**
- Added my challenge information

### CODE REVIEW

**Comment by kimschles** [comment]
Hi @Sossenbinder! 

Good work on your project and writeup. 

One question: Was the message queue deployed in a DigitalOcean Kubernetes cluster? That's one of the requirements as listed in the [Success Criteria](https://www.digitalocean.com/community/pages/kubernetes-challenge#anchor--success-criteria). 

I can't tell if the production cluster was built using Kind or DigitalOcean Kubernetes. 

Let me know! 

--Kim

**Review by kimschles — CHANGES_REQUESTED** [review]
Please update the project readme to show that you used DigitalOcean Kubernetes for at least part of the project.

**Comment by Sossenbinder** [comment]
> Hi @Sossenbinder!
> 
> Good work on your project and writeup.
> 
> One question: Was the message queue deployed in a DigitalOcean Kubernetes cluster? That's one of the requirements as listed in the [Success Criteria](https://www.digitalocean.com/community/pages/kubernetes-challenge#anchor--success-criteria).
> 
> I can't tell if the production cluster was built using Kind or DigitalOcean Kubernetes.
> 
> Let me know!
> 
> --Kim

Hey Kim,

sure! True, I didn't think of that, but that is obviously not visible right away given only the IP.

I did use a DigitalOcean Load Balancer and Kubernetes cluster, see this screenshot:

image

I have to admit, that I didn't take care of a proper domain name setup, because I saw that DigitalOcean didn't have their own domain server but relies on a third party service, and I figured this might be a bit too much work for a simple demo.

**Comment by kimschles** [comment]
Great. Thanks for the clarification!!

**Pull request merged**
