### PR TITLE
My Way Of Installing A Wordpress Website With Managed MySQL Using Docker

### PR DESCRIPTION
**Pull request by sectorg33**
digitaloceanchallengetwo
Showcasing My Way Of Deploying A Wordpress Using MySQL Managed Database

first and foremost install docker with:- 
_curl -fsSL https://get.docker.com -o get-docker.sh 
DRY_RUN=1 sh ./get-docker.sh_

test the installation with:- 
_docker run hello-world_

then install a wordpress image with:- 
_docker pull wordpress_

first list the images with:- 
_docker ps -a_ (and note the container ID) 
then start the container if it's stopped with:- 
_docker start "containerid"_ 
then log into the docker with:- 
docker exec -it "containerid" bash

then first make an update to the image:- 
_apt update_

then connect to your created mysql managed database on digital ocean with:- 
_mysql -u user -p -h host_uri -P port_

Create a Wordpress User Account with:-
 _CREATE USER 'wordpressuser'@localhost IDENTIFIED WITH mysql_native_password BY 'your_database_password';_

Grant permisions to the newly created user on the wordpress database with:- 
_GRANT ALL ON wordpress.* TO 'wordpressuser'@localhost;_

Then Type:- 
_exit_

**Then edit your wp-config file and replace these values with your own credentials**

/** The name of the database for WordPress */ define( 'DB_NAME', 'your_database_name' );

/** MySQL database username */ define( 'DB_USER', 'your_database_username' );

/** MySQL database password */ define( 'DB_PASSWORD', 'your_database_password' );

/** MySQL hostname */ define( 'DB_HOST', 'your_database_host:25060' );

/** Database charset to use in creating database tables. */ define( 'DB_CHARSET', 'utf8' );

/** The database collate type. Don't change this if in doubt. */ define( 'DB_COLLATE', '' );

define('FS_METHOD', 'direct');

save and close

**Then head over to your browser to start the installation.**

### CODE REVIEW

**Review by OliverMensahDev — CHANGES_REQUESTED** [review]
Hi @sectorg33 !

Thank you for the write-up. Can you share more in the write-up about the installation project and also with pictorial references in the write-up rather than just saying `Then head over to your browser to start the installation.`

In the write-up, you deployed WordPress to Kubernetes. One of the requirements for earning a prize is to deploy your project in a DigitalOcean Managed Kubernetes cluster. It seems just install third-party software, WordPress, rather than deploying your own project, is this right?

**Comment by sectorg33** [comment]
halo mrs oliver, the credit i was provided with $60 was to showcase
how to deploy a managed mysql database cluster. so in this i was
trying to showcase that you can deploy multiple website using one
managed mysql database cluster. i didn't apply to deploy on a managed
kubernetes cluster. i applied to deploy on a managed mysql database
cluster. you get?

**Comment by sectorg33** [comment]
halo Mrs. Olivier, originally this was my writeup about the managed
mysql database cluster






Requirements:-
- Windows Or Linux Server Installed With Either Apache Or Ngnix
- Digital Ocean Managed MySQL Database Cluster
- MySQL Workbench
-


Create a scalable MySQL Database Cluster Hosting Multiple Sites. On
the same cluster, create another administrative user with MySQL Native
Password Encryption 5+ legacy and save the following connection
details regarding the cluster:- Username, Password, Host And The Port.

Then Open MySQL Workbench and add the connection details. Make Sure
You Test The Connection. Sometimes
"db-mysql-nyc3-05157-do-user-8532287-0.b.db.ondigitalocean.com" shows
that it's an invalid hostname but try to ping it and then use the ip
address instead.

Then open the newly added user account using MySQL Workbench. Then
Create a database where you are going to import the database file
"database_to_import.sql". Make sure that you use MySQL Workbench to
create the database and don't use the digital ocean dashboard because
the database import may fail to work with errors.

There after import the database file into the newly created database
by clicking Start Import And The Import Should Be Successful As Shown
Above:-

Then head over to the location on your server where you uploaded the
website files and open the admin/config.php file and set it as shown
below and then save it:-

Then head over to your browser and visit the url where your server is
running and your newly created website should be up and running like
shown below:-

You can as well visit the admin panel
http://127.0.0.1/testing/admin/login.php and start tuning and managing
the website to your own desires.

Role          Email             Password
Super Admin ***@***.***    1234
Admin       ***@***.***     1234
Publisher   ***@***.*** 1234

In just ten minutes, you have a website up and running using the
incredible digital ocean scalable MySQL Database Cluster With High
availability – The cluster can be configured to span across multiple
availability zones (physical data centers) Performance – Usually the
cloud provider installs the database on SSD storage. Security –
Encryption at rest and in transit.

The greatest benefit you will achieve using digital ocean's managed
sql database cluster is:-
-It's high availability because the cluster can be configured to span
across multiple data centers.
-Security Vault – Encryption at rest and in motion regardless of where
it is used, moved or stored.
-Monitoring – Built-in the service.

**Comment by sectorg33** [comment]
Leave Alone that one

**Comment by OliverMensahDev** [comment]
The file should be a markdown file that's it must have ".md" as an extension. 

Also, you shouldn't delete the template.md file.

**Comment by kimschles** [comment]
Hi @sectorg33, 

[One of the requirements for completing the challenge](https://www.digitalocean.com/community/pages/kubernetes-challenge#anchor--success-criteria) is to deploy something in a DigitalOcean Kubernetes cluster. Since there's no DigitalOcean Kubernetes cluster involved in your writeup, it does not meet the criteria, and we can't merge your pull request.

**Pull request closed without merging**
