### PR TITLE
D34DPlayer's Kubernetes challenge

### PR DESCRIPTION
**Pull request by D34DPlayer**
Deploy an internal container registry

### CODE REVIEW

**Review by kimschles — CHANGES_REQUESTED** [review]
Hi @D34DPlayer! 

I can't access the github repo you linked. Is the repo private? 

Please make that repo public or update the link to one we can see and we can review. :)

**Comment by D34DPlayer** [comment]
My bad, i should be a public repository now

**Comment by kimschles** [comment]
@D34DPlayer I can access that repo now. :) 

You'll need to make one change before I can merge the PR: I need to see some evidence that you used a DigitalOcean Kubernetes cluster. You can share a screenshot or add a sentence about it in your readme. Let me know when that's added and I'll take a look.

**Comment by D34DPlayer** [comment]
@kimschles 
I destroyed the cluster already, so I don't have any screenshot, but I added a section about it in my readme.

**Comment by D34DPlayer** [comment]
Bump

**Comment by kimschles** [comment]
My bad, I thought I merged this! Thank you for reminding me.

**Pull request merged**
