### PR TITLE
Create wyrihaximus-kubernetes-challenge.md

### PR DESCRIPTION
**Pull request by WyriHaximus**
## Name of Project 
* Deploy a solution for policy enforcement

## Link to Your Github or Gitlab Repo
* https://github.com/WyriHaximus/do-k8s-challenge

## Link to Your Project Writeup
* https://blog.wyrihaximus.net/2021/12/the-digitalocean-challenge-implementing-kyverno/

## Contact Info
* Name: Cees-Jan Kiewiet
* Twitter: https://twitter.com/wyrihaximus
* Blog: https://blog.wyrihaximus.net/

## Misc 
* Was a lot of fun!
* Learned tons

### CODE REVIEW

**Review by OliverMensahDev — CHANGES_REQUESTED** [review]
Awesome work @WyriHaximus.

With the steps of creating your cluster, can you include in your write-up some screenshots of the DO  dashboard or screenshots of a few commands that you used in creating the DOKS?

**Comment by WyriHaximus** [comment]
@OliverMensahDev sure will update it later today :+1:

**Comment by WyriHaximus** [comment]
@OliverMensahDev Updated the post, it might take up to 24 hours after I posted this comment for the CDN to be updated and the changes are visible.

**Comment by OliverMensahDev** [comment]
Awesome.
I will go ahead to merge it once everything is up to date on the blog.

**Comment by WyriHaximus** [comment]
Awesome! Probably want to hook up cache invalidation when deploying, but this also works fine in 99% of the cases

**Comment by OliverMensahDev** [comment]
Works now.
Thank you.

**Review by OliverMensahDev — APPROVED** [review]

**Pull request merged**
