### PR TITLE
add info

### PR DESCRIPTION
**Pull request by everythingeverywhere**
added my info

### CODE REVIEW

**Review by OliverMensahDev — CHANGES_REQUESTED** [review]
Kindly reformat the markdown file so it becomes more readable.
Also, make sure you follow the submission format

**Comment by kimschles** [comment]
Hi @everythingeverywhere! 

We need you to make one change before we merge your PR. Please use the formatting in the [template](https://github.com/do-community/kubernetes-challenge/blob/main/template.md) file to structure your markdown file. Once that's fixed, you'll be good to go!

**Comment by everythingeverywhere** [comment]
@kimschles and @OliverMensahDev thanks for the feedback added changes requested.

**Comment by kimschles** [comment]
great work! thanks for making that change. 🎉

**Pull request merged**
