### PR TITLE
Add harkiratsm-kubernetes-challenge.md

### PR DESCRIPTION
**Pull request by harkiratsm**
Project - Deploy scalable NoSQL database cluster

### CODE REVIEW

**Review by OliverMensahDev — CHANGES_REQUESTED** [review]
Awesome work @harkiratsm 

While skimming through your write-up, I couldn't find where you made mention of spinning up DigitalOcean Kubernetes Cluster either through the UI, doctl, terraform, etc?

In case you did while working on the project, kindly add screenshots of those in your writeup.

**Comment by harkiratsm** [comment]
@OliverMensahDev  @kimschles 
Basically I didn't used the digital ocean kubernetes cluster because I thought it was not required  also I  followed a basic approach to make it understandable to the folks . Also I found out that some of the merged PR didn't used it either .

**Comment by harkiratsm** [comment]
@OliverMensahDev 
I have used minikube for this particular project .
If you want me to add steps on getting started with DOKS , I can surely add up those to this project.
Please tell me what to do . 🙏

**Comment by harkiratsm** [comment]
I have added the steps you can checkout [here](https://github.com/harkiratsm/DigitalOcean-Kubernetes-Challenge/blob/main/Readme.md)
@OliverMensahDev

**Review by OliverMensahDev — APPROVED** [review]

**Pull request merged**
