### PR TITLE
Create Sourabh Mathur-kubernetes-challenge.md

### PR DESCRIPTION
**Pull request by smmath14**

### CODE REVIEW

**Comment by smmath14** [comment]
Deploy MongoDB Cluster on Kubernetes (NO SQL)

**Review by OliverMensahDev — CHANGES_REQUESTED** [review]
The PR should contain just one markdown file that contains the information from the submission format.

**Review by smmath14 — COMMENTED** [review]
I have updated it , please take a look

**Comment by smmath14** [comment]
Sir,
I have made necessary changes you can now review it now, sorry for
inconvience

**Comment by OliverMensahDev** [comment]
Awesome.

Concerning the write-up can you share screenshots of the commands or the DO dashboard that shows you created the DOKS cluster.

**Comment by smmath14** [comment]
ya sure

**Comment by smmath14** [comment]
> _No description provided._

Sir till now my PR isn't merge can I get a reason for it

**Comment by OliverMensahDev** [comment]
Screen Shot 2022-01-07 at 4 09 21 PM

Can you add a few screenshots here about how you created the cluster?

**Comment by smmath14** [comment]
> Screen Shot 2022-01-07 at 4 09 21 PM
> 
> Can you add a few screenshots here about how you created the cluster?

Screenshot 2022-01-07 at 10 12 42 PM
Screenshot 2022-01-07 at 10 12 46 PM
Screenshot 2022-01-07 at 10 12 51 PM
Screenshot 2022-01-07 at 10 13 02 PM
Screenshot 2022-01-07 at 10 13 10 PM
1. first i will click con create option on left hand side 
2. then will choose kubernetes from drop down menu
3. then will choose all desired option and fill option according to our choice
4. then will click on create at down 
after that it will going to take some time for creating cluster

**Comment by smmath14** [comment]
sir if have updated about your question kindly have a look into it , thank you

**Comment by OliverMensahDev** [comment]
Oh sorry, I should have been specific. 
They should be added in your README file as part of the blog post.

**Comment by smmath14** [comment]
Dear sir,
I have uploaded all screenshot of how to create cluster, connect to mongo-db, and terminal part as well, now here you can review my PR and merge it , I am now ready to go, sorry for the inconvenience.
Thank you

**Comment by smmath14** [comment]
Sir now you can review my PR . I have made changes in readme file. You can checkout

**Comment by smmath14** [comment]
@OliverMensahDev @kimschles you can have a look into my PR

**Review by OliverMensahDev — APPROVED** [review]

**Pull request merged**
