### PR TITLE
Devandi readme

### PR DESCRIPTION
**Pull request by devandi**

### CODE REVIEW

**Review by OliverMensahDev — CHANGES_REQUESTED** [review]
Awesome work @devandi .

Concerning your writeup, kindly share with us how you created the cluster together how you managed your application or services with it A

**Comment by devandi** [comment]
@OliverMensahDev thanks for the feedback. I updated the writeup with more information about how I created the cluster.

**Comment by OliverMensahDev** [comment]
Awesome.

In case you have screenshots of those clusters you created or how you went about creating them would be nice. 
Add them in the write-up

**Comment by OliverMensahDev** [comment]
@devandi, are you still working on this?

**Comment by devandi** [comment]
@OliverMensahDev sorry for the late answer. I don't really have screenshots from creating the cluster because I created it with terraform apply. ;-)

That's why I cannot include any screenshots in the writeup. Hope that is okay too?

**Comment by kimschles** [comment]
Your terraform files show that you created the cluster with DigitalOcean Kubernetes. Good work! Thank you for responding to our comments. :)

**Pull request merged**
